parameters:
    mailer.from:
        'robot@test.dev': '"Robot, test.dev"'

services:
    app.twig.app_extension:
        class:     AppBundle\Twig\AppExtension
        arguments:
            - '@app.transLit'
        public:    false
        tags:
            - { name: twig.extension }

    app.transLit:
        class:     AppBundle\Helper\TransLitHelper
        tags:
            - { name: app.transLit }

    app.authentication_listener:
        class: AppBundle\Listener\AuthenticationListener
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }

    app.authentication_handler:
        class: AppBundle\Handler\AuthenticationHandler
        arguments:
            - '@logger'

    app.registration:
        class: AppBundle\Service\RegistrationService
        arguments:
            - '@logger'
            - '@service_container'
            - '@doctrine.orm.entity_manager'

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: AppBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }

    app.user.resetting_mailer:
        class: AppBundle\Service\Mailer
        arguments:
            - '@mailer'
            - '@service_container'